- hosts: localhost
  tasks:
    - name: "Create the file /tmp/x"
      file:
        path: /tmp/x
        state: touch
    - name: "Create the file /tmp/y"
      file:
        path: /tmp/y
        state: touch
    - name: "Create the file /tmp/z"
      file:
        path: /tmp/z
        state: touch
    - name: "Install htop package"
      become: true
      package:
        name: htop
        state: present
    - name: "Install netcat package"
      become: true
      package:
        name: netcat
        state: present
    - name: "Create a foo user"
      become: true
      user:
        name: "foo"