---
- hosts: all
  vars:
    users: []
  tasks:
  - name: Update apt-get repo and cache
    become: true
    apt:
      update_cache: yes
      force_apt_get: yes
      cache_valid_time: 3600

  - name: "Install dependencies"
    become: true
    package:
      name: "{{ item }}"
      state: present
    loop:
    - nodejs
    - npm
    - ansible

  - name: "Install npm dependencies"
    become: true
    command:
      chdir: /vagrant
      cmd: npm install
