---
- hosts: all
  vars:
    users:
    - name: ivoputzer
      comment: Ivo von Putzer Reibegg
      password: $6$IdVtXdaOmTYWw7xW$jQvaLuYWJobdC/k1dzmY61wyvYF1YLEl4AVzqUxAVVUik5HqflLbgI/ALnRsKBNPfgOzRw03zs742lo9HwYP.1
      state: present
    - name: lorenzoberetta92
      comment: Lorenzo Beretta
      password: $5$SY7qq5FoIgj1KmNB$a3UTM.qANiR6HR6ugLbSeIF9EumaxS0gJlIHUVGMU89
      state: absent
    - name: mrVerna
      comment: Francesco Vernacchia
      password: $5$SY7qq5FoIgj1KmNB$a3UTM.qANiR6HR6ugLbSeIF9EumaxS0gJlIHUVGMU89
      state: present
    - name: danielescorsino
      comment: Daniele Scorsino
      password: $5$SY7qq5FoIgj1KmNB$a3UTM.qANiR6HR6ugLbSeIF9EumaxS0gJlIHUVGMU89
      state: present
  handlers:
  - name: restart sshd
    service:
      name: sshd
      state: restarted
  tasks:
  - name: Update apt-get repo and cache
    become: true
    apt:
      update_cache: yes
      force_apt_get: yes
      cache_valid_time: 3600

  - name: "Install dependencies"
    become: true
    package:
      name: "{{ item }}"
      state: present
    loop:
    - nodejs
    - npm

  - name: Add users with primary group 'sudo'
    ansible.builtin.user:
      name: "{{ item.name }}"
      comment: "{{ item.comment }}"
      password: "{{ item.password }}"
      update_password: always
      group: sudo
      shell: /bin/bash
      create_home: true
      state: "{{ item.state }}"
      remove: yes
    with_items: "{{ users }}"

  - name: Add authorized_keys without validating the certs
    authorized_key:
      user: "{{ item.name }}"
      state: present
      key: "https://github.com/{{ item.name }}.keys"
      validate_certs: false
    when: item.state == 'present'
    with_items: "{{ users }}"

  - name: Disable ssh access to root user
    ansible.builtin.lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: ^PermitRootLogin
      line: PermitRootLogin yes
      state: present
    notify: restart sshd

  - name: Create project directory
    file:
      path: /app
      state: directory

  - name: Copy project into remote directory
    copy:
      src: ./
      dest: /app

  - name: "Install project dependencies"
    become: true
    command:
      chdir: /app
      cmd: npm install

  - name: "Build project assets"
    become: true
    command:
      chdir: /app
      cmd: npm run build --if-present

  # - name: "Start project"
  #   become: true
  #   command:
  #     chdir: /app
  #     cmd: npm start&
