name: "Node Build"
on:
  push:
    branches: [master]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: refs/head/master
    - uses: actions/setup-node@master
      with:
        node-version: '14'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
